[env]
platform = teensy
board = teensy40
framework = arduino
upload_protocol = teensy-cli
board_microros_distro = humble
board_microros_transport = serial

lib_deps =
    https://github.com/micro-ROS/micro_ros_arduino.git
    waspinator/AccelStepper @ ^1.64

lib_ignore = 
    NativeEthernet
    Ethernet
    FNET

build_flags = 
    -D MICRO_ROS_BUFFER_SIZE=2048
    -L .pio/libdeps/$PIOENV/micro_ros_arduino/src/imxrt1062/fpv5-d16-hard/
    -lmicroros

[env:manual_control]
build_src_filter = +<main_manual.cpp> -<main_fsm.cpp>
build_flags = 
    ${env.build_flags}
    -D NODE_NAME=\"xaxis_manual\"
    -D TOPIC_NAME=\"xaxis_cmd\"

[env:xaxis_fsm]
build_src_filter = -<main_manual.cpp> +<main_fsm.cpp>
build_flags = 
    ${env.build_flags}
    -D NODE_NAME=\"xaxis_node\"
    -D TOPIC_NAME=\"risc_command\"