[env]
platform = teensy
board = teensy40
framework = arduino
upload_protocol = teensy-cli
board_microros_distro = humble
board_microros_transport = serial

lib_deps =
    https://github.com/micro-ROS/micro_ros_arduino.git
    waspinator/AccelStepper @ ^1.64

build_flags = 
    -D MICRO_ROS_BUFFER_SIZE=2048
    -L .pio/libdeps/$PIOENV/micro_ros_arduino/src/imxrt1062/fpv5-d16-hard/
    -lmicroros

[env:zl_manual]
build_flags = 
    ${env.build_flags}
    -D NODE_NAME=\"zl_node\"
    -D TOPIC_NAME=\"zl_manual_cmd\"

[env:zl_fsm]
build_flags = 
    ${env.build_flags}
    -D NODE_NAME=\"zl_node\"
    -D SUB_TOPIC=\"z_command\"
    -D PUB_TOPIC=\"zl_status\"
    -D ZL_TARGET_INDEX=4  ;CMD_Z_LEFT_TARGET from risc_bus.h
    -D HW_ID=3.0         ;Unique ID for ZL